//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на привет
        ///привета
        ///привету
        ///привете
        ///приветом
        ///приветы
        ///приветов
        ///приветам
        ///приветах
        ///приветами
        ///а
        ///негаа
        ///заа
        ///авраа
        ///исаа
        ///ба
        ///аба
        ///баба
        ///габа
        ///жаба
        ///афразиаба
        ///каба
        ///слаба
        ///раба
        ///араба
        ///таба
        ///штаба
        ///деба
        ///хлеба
        ///неба
        ///полнеба
        ///греба
        ///погреба
        ///треба
        ///ястреба
        ///феба
        ///чеба
        ///нежба
        ///служба
        ///дружба
        ///тяжба
        ///изба
        ///загиба
        ///изгиба
        ///погиба
        ///сгиба
        ///скриба
        ///приба
        ///хиба
        ///ошиба
        ///пошиба
        ///отшиба
        ///ушиба
        ///лейба
        ///лба
        ///колба
        ///столба
        ///амба
        ///гамба
        ///памба
        ///бомба
        ///ромба
        ///клумба
        ///колумба
        ///румба
        ///бакенба
        ///монба
        ///оба
        ///вдоба
        ///худоба
        ///лоба
        ///жалоба
        ///злоба
        ///крутолоба
        ///озноба
        ///гроба
        ///гардероба
        ///короба
        ///проба
        ///утроба
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RussianWords {
            get {
                return ResourceManager.GetString("RussianWords", resourceCulture);
            }
        }
    }
}
